version: '3.8'

services:
  bootstrapper:
    image: ghcr.io/10d9e/shard:latest
    command: shard --listen-address /ip4/10.6.0.5/tcp/40837 --secret-key-seed 1 provide --db-path .db --refresh-interval 10
    ports:
      - "40837:40837"
    networks:
      shard_network_ghcr:
        ipv4_address: 10.6.0.5

  provider:
    image: ghcr.io/10d9e/shard:latest
    command: >
      /bin/sh -c "
      mkdir -p .shard &&
      echo 'bootstrapper = \"/ip4/10.6.0.5/tcp/40837/p2p/12D3KooWPjceQrSwdWXPyLLeABRXmuqt69Rg3sBYbU1Nft9HyQ6X\"' > .shard/conf.toml &&
      shard provide --db-path .db
      "
    depends_on:
      - bootstrapper
    scale: 9
    networks:
      - shard_network_ghcr

  client:
    container_name: client
    image: ghcr.io/10d9e/shard:latest
    command:  >
      /bin/sh -c "
      mkdir -p .shard &&
      echo 'bootstrapper = \"/ip4/10.6.0.5/tcp/40837/p2p/12D3KooWPjceQrSwdWXPyLLeABRXmuqt69Rg3sBYbU1Nft9HyQ6X\"' > .shard/conf.toml &&
      tail -f /dev/null
      "
    networks:
      - shard_network_ghcr

networks:
  shard_network_ghcr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.6.0.0/16
         gateway: 10.6.0.1
