# fly.toml app configuration file generated for shard on 2023-11-23T19:54:50-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "shard"
primary_region = "yul"

[build]
  dockerfile = "docker/Dockerfile"

[env]
  LISTEN_ADDR = "/ip4/0.0.0.0/tcp/40837"

[http_service]
  internal_port = 40837
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
