name: Build and Deploy to GHCR

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: write-all
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to GHCR
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

    - name: Get Version from Cargo.toml
      id: version
      run: echo ::set-output name=version::$(cat docker/Cargo.toml | grep -Po '(?<=version = ")[^"]*')

    - name: Build and Push Docker Image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/my-image:${{ steps.version.outputs.version }} -f docker/Dockerfile .
        docker push ghcr.io/${{ github.repository_owner }}/my-image:${{ steps.version.outputs.version }}
        
    - name: Build and Push Docker Image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/shard:latest -f docker/Dockerfile .
        docker push ghcr.io/${{ github.repository_owner }}/shard:latest
        docker build -t ghcr.io/${{ github.repository_owner }}/shard:${{ steps.version.outputs.version }} -f docker/Dockerfile .
        docker push ghcr.io/${{ github.repository_owner }}/shard:${{ steps.version.outputs.version }}
