name: Build and Deploy to GHCR

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: write-all
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to GHCR
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

    - name: Install tomlq
      run: |
        curl -sSL https://github.com/pappasam/tomlq/releases/download/v1.2.0/tomlq_linux_amd64 -o tomlq
        chmod +x tomlq
        sudo mv tomlq /usr/local/bin/
      if: runner.os == 'Linux'
    
    - name: Get Version from Cargo.toml
      id: version
      run: |
        version=$(tomlq -r .package.version docker/Cargo.toml)
        echo "::set-output name=version::$version"
      shell: bash
        
    - name: Build and Push Docker Image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/shard:latest -t ghcr.io/${{ github.repository_owner }}/shard:${{ steps.version.outputs.version }} -f docker/Dockerfile .
        docker push ghcr.io/${{ github.repository_owner }}/shard:latest
        docker push ghcr.io/${{ github.repository_owner }}/shard:${{ steps.version.outputs.version }}
